set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle.vim
call vundle#begin()
Plugin 'Vundlevim/vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'majutsushi/tagbar'
Plugin 'julialang/julia-vim'
Plugin 'townk/vim-autoclose'
Plugin 'scrooloose/nerdcommenter'
Plugin 'kien/ctrlp.vim'

call vundle#end()
filetype plugin indent on

map <F2> :NERDTreeToggle<CR>
map <F4> :TagbarToggle<CR>

set autochdir
set expandtab
set shiftwidth=4
set softtabstop=4
let c_space_errors = 1
